' Gambas module file

Function binary_search(list As Float[], item As Float) As Variant
  Dim low, high, Midd, guess As Float
  low = 0
  high = list.Length - 1
  While low <= high
    Midd = (low + high)
     guess = list[Midd]
     If guess = item Then
       Return Midd
     Else If guess > item Then
       high = Midd - 1
     Else 
       low = Midd + 1    
     Endif
  Wend 
   Return Null
End

Public Sub Main()

Dim my_list As New Float[]
my_list = [1, 3, 5, 7, 9]
Print binary_search(my_list, 3) '1
Print binary_search(my_list, -1) 'null
End
